apiVersion: v1
kind: Service
metadata:
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    protocol: TCP
    name: "ftps"
    targetPort: 21
  - port: 10092
    name: "range1"
    targetPort: 10092
  - port: 10091
    name: "range2"
    targetPort: 10091
  - port: 10090
    name: "range3"
    targetPort: 10090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10092
        - containerPort: 10091
        - containerPort: 10090
