apiVersion: v1
kind: Service
metadata:
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
